import { jsPDF } from "jspdf";

interface InvoiceData {
  invoiceNumber: string;
  periodStart: string;
  periodEnd: string;
  fromEntity: string;
  toEntity: string;
  totalClasses: number;
  totalAmountIdr: number;
  ratePerClassIdr: number;
  generatedAt: Date | string;
}

interface LineItemData {
  orphanageName: string;
  classCount: number;
  ratePerClassIdr: number;
  subtotalIdr: number;
}

function formatIdr(amount: number): string {
  return amount.toLocaleString("id-ID");
}

function formatPeriod(start: string, end: string): string {
  const date = new Date(start + "T00:00:00");
  return date.toLocaleDateString("en-US", { month: "long", year: "numeric" });
}

/**
 * Generate a PDF invoice and return it as a Buffer.
 */
export function generateInvoicePdf(
  invoice: InvoiceData,
  lineItems: LineItemData[]
): Buffer {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // ─── Header ──────────────────────────────────────────────────────
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", margin, y + 10);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(invoice.invoiceNumber, pageWidth - margin, y + 4, { align: "right" });

  const genDate = new Date(invoice.generatedAt);
  doc.text(
    `Date: ${genDate.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    pageWidth - margin,
    y + 10,
    { align: "right" }
  );

  y += 20;

  // Divider line
  doc.setDrawColor(10, 64, 12); // green-700
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ─── From / To ───────────────────────────────────────────────────
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM:", margin, y);
  doc.text("TO:", pageWidth / 2 + 10, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(invoice.fromEntity, margin, y);
  doc.text(invoice.toEntity, pageWidth / 2 + 10, y);
  y += 10;

  // ─── Period ──────────────────────────────────────────────────────
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Period:", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(formatPeriod(invoice.periodStart, invoice.periodEnd), margin + 18, y);
  y += 12;

  // ─── Table Header ────────────────────────────────────────────────
  const colX = {
    num: margin,
    orphanage: margin + 10,
    classes: pageWidth - margin - 80,
    rate: pageWidth - margin - 50,
    subtotal: pageWidth - margin,
  };

  doc.setFillColor(245, 245, 240); // sand-50
  doc.rect(margin, y - 4, pageWidth - margin * 2, 8, "F");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("#", colX.num, y);
  doc.text("Orphanage", colX.orphanage, y);
  doc.text("Classes", colX.classes, y, { align: "right" });
  doc.text("Rate (IDR)", colX.rate, y, { align: "right" });
  doc.text("Subtotal (IDR)", colX.subtotal, y, { align: "right" });
  y += 8;

  // ─── Table Rows ──────────────────────────────────────────────────
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  lineItems.forEach((item, index) => {
    // Check if we need a new page
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    doc.text(String(index + 1), colX.num, y);
    doc.text(item.orphanageName, colX.orphanage, y);
    doc.text(String(item.classCount), colX.classes, y, { align: "right" });
    doc.text(formatIdr(item.ratePerClassIdr), colX.rate, y, { align: "right" });
    doc.text(formatIdr(item.subtotalIdr), colX.subtotal, y, { align: "right" });
    y += 6;
  });

  // If no line items
  if (lineItems.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.text("No classes recorded for this period", margin + 10, y);
    y += 6;
  }

  y += 4;

  // ─── Total ───────────────────────────────────────────────────────
  doc.setDrawColor(10, 64, 12);
  doc.setLineWidth(0.3);
  doc.line(colX.rate - 20, y - 2, colX.subtotal, y - 2);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL", colX.rate - 20, y + 4);
  doc.text(`IDR ${formatIdr(invoice.totalAmountIdr)}`, colX.subtotal, y + 4, {
    align: "right",
  });

  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    `${invoice.totalClasses} classes × IDR ${formatIdr(invoice.ratePerClassIdr)}/class`,
    colX.rate - 20,
    y + 4
  );

  // ─── Footer ──────────────────────────────────────────────────────
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Meant for Greatness", pageWidth / 2, footerY, {
    align: "center",
  });

  // Return as Buffer
  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}
